# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  check-and-build-only:
    executor: docker/machine
    environment:
      DOCKER_LOGIN: ""
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          path: docker/opsys/ubuntu/20.04
          # registry: my.docker.registry

workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only
