# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only

jobs:
  prepwork:
    steps:
      - run: REPO_NAME=$(echo ${$CIRCLE_PROJECT_USERNAME} | tr A-Z a-z)
      - run: IMAGE_NAME=$(echo ${$CIRCLE_PROJECT_REPONAME} | tr A-Z a-z)
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $REPO_NAME/$IMAGE_NAME
          path: docker/opsys/ubuntu/20.04
          # registry: my.docker.registry
