# ToDo: Add Docker 21.04
#FROM ubuntu:21.04
#
#RUN apt-get update -y --fix-missing && \
#    apt-get upgrade -y
#
#WORKDIR /opt/
#
# To Do: Create user account (service user)
# To Do: Install any security tooling, etc.
